# -*- coding: utf-8 -*-

# Scrapy settings for xiaoqu_crawl project
#
# For simplicity, this file contains only settings considered important or
# commonly used. You can find more settings consulting the documentation:
#
#     https://doc.scrapy.org/en/latest/topics/settings.html
#     https://doc.scrapy.org/en/latest/topics/downloader-middleware.html
#     https://doc.scrapy.org/en/latest/topics/spider-middleware.html

BOT_NAME = 'xiaoqu_crawl'

SPIDER_MODULES = ['xiaoqu_crawl.spiders']
NEWSPIDER_MODULE = 'xiaoqu_crawl.spiders'

# Crawl responsibly by identifying yourself (and your website) on the user-agent
# USER_AGENT = 'xiaoqu_crawl (+http://www.yourdomain.com)'

# Obey robots.txt rules
ROBOTSTXT_OBEY = False

# Configure maximum concurrent requests performed by Scrapy (default: 16)
# CONCURRENT_REQUESTS = 1

# Configure a delay for requests for the same website (default: 0)
# See https://doc.scrapy.org/en/latest/topics/settings.html#download-delay
# See also autothrottle settings and docs
# DOWNLOAD_DELAY = 3
# The download delay setting will honor only one of:
# CONCURRENT_REQUESTS_PER_DOMAIN = 16
# CONCURRENT_REQUESTS_PER_IP = 16

# Disable cookies (enabled by default)
# COOKIES_ENABLED = False

# Disable Telnet Console (enabled by default)
# TELNETCONSOLE_ENABLED = False

# Override the default request headers:
# DEFAULT_REQUEST_HEADERS = {
#   'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
#   'Accept-Language': 'en',
# }

# Enable or disable spider middlewares
# See https://doc.scrapy.org/en/latest/topics/spider-middleware.html
# SPIDER_MIDDLEWARES = {
#    'xiaoqu_crawl.middlewares.XiaoquCrawlSpiderMiddleware': 543,
# }

# Enable or disable downloader middlewares
# See https://doc.scrapy.org/en/latest/topics/downloader-middleware.html
# DOWNLOADER_MIDDLEWARES = {
#    'xiaoqu_crawl.middlewares.XiaoquCrawlDownloaderMiddleware': 543,
# }

# Enable or disable extensions
# See https://doc.scrapy.org/en/latest/topics/extensions.html
# EXTENSIONS = {
#    'scrapy.extensions.telnet.TelnetConsole': None,
# }

# Configure item pipelines
# See https://doc.scrapy.org/en/latest/topics/item-pipeline.html
ITEM_PIPELINES = {
    'xiaoqu_crawl.pipelines.XiaoquCrawlPipeline': 300,
}

# Enable and configure the AutoThrottle extension (disabled by default)
# See https://doc.scrapy.org/en/latest/topics/autothrottle.html
# AUTOTHROTTLE_ENABLED = True
# The initial download delay
# AUTOTHROTTLE_START_DELAY = 5
# The maximum download delay to be set in case of high latencies
# AUTOTHROTTLE_MAX_DELAY = 60
# The average number of requests Scrapy should be sending in parallel to
# each remote server
# AUTOTHROTTLE_TARGET_CONCURRENCY = 1.0
# Enable showing throttling stats for every response received:
# AUTOTHROTTLE_DEBUG = False

# Enable and configure HTTP caching (disabled by default)
# See https://doc.scrapy.org/en/latest/topics/downloader-middleware.html#httpcache-middleware-settings
# HTTPCACHE_ENABLED = True
# HTTPCACHE_EXPIRATION_SECS = 0
# HTTPCACHE_DIR = 'httpcache'
# HTTPCACHE_IGNORE_HTTP_CODES = []
# HTTPCACHE_STORAGE = 'scrapy.extensions.httpcache.FilesystemCacheStorage'

import logging

# 日志打印开关
LOG_ENABLED = True
LOG_LEVEL = logging.INFO
LOG_FILE = 'spider.log'
LOG_STDOUT = True

# mongodb数据库配置
MONGO_URI = 'mongodb://192.168.110.51:27017'
MONGO_DB = "xuqiang"
MONGO_CONNECTION = "xiaoqu_info_all"
MYCookie = '___rl__test__cookies=1540783879590; aQQ_ajkguid=52616037-C06C-5C9D-9F61-BBEDAAEE5A93; twe=2; sessid=65A95901-612D-ADBB-7497-F059009481C3; 58tj_uuid=cf3b4d88-71ab-439e-8305-6d8bf1e7bd54; als=0; _ga=GA1.2.495209661.1540519851; isp=true; Hm_lvt_c5899c8768ebee272710c9c5f365a6d8=1540520326; ajk_member_captcha=dc80c25bb452dd6c69e3de74c6c88a9c; propertys=obkghx-ph6qgn_; Hm_lpvt_c5899c8768ebee272710c9c5f365a6d8=1540532861; wmda_uuid=982871dbb3789e1f3ac80699c275bedf; wmda_new_uuid=1; wmda_visited_projects=%3B6145577459763; OUTFOX_SEARCH_USER_ID_NCOO=474938652.6946653; browse_comm_ids20=366473; Ref=https%3A%2F%2Fm.anjuke.com%2Fans%2Fmap%2F%3Fadr%3D%25E5%25AE%2589%25E9%25A1%25BA%25E5%25B8%2582%25E4%25B8%25AD%25E5%258D%258E%25E5%258D%2597%25E8%25B7%25AF%25E5%2592%258C%25E5%25A1%2594%25E5%25B1%25B1%25E4%25B8%259C%25E8%25B7%25AF%25E7%259A%2584%25E4%25BA%25A4%25E5%258F%2589%25E5%258F%25A3%26lng%3D0%26lat%3D0%26tp%3Dcomm%26id%3D773546; ctid=15; lps="/cd/xiaoqu/|https://m.anjuke.com/captcha-verify/?callback=shield&from=antispam&serialID=c01c5738f45fe56efcc8a1a067cac0f6_64cef457f47d483299787853e1809f6d&history=aHR0cHM6Ly9tLmFuanVrZS5jb20vY2QveGlhb3F1Lw%3D%3D"; wmda_session_id_6145577459763=1540794744030-65825f5e-d663-3c16; init_refer=https%253A%252F%252Fm.anjuke.com%252Fcaptcha-verify%252F%253Fcallback%253Dshield%2526from%253Dantispam%2526serialID%253Dc01c5738f45fe56efcc8a1a067cac0f6_64cef457f47d483299787853e1809f6d%2526history%253DaHR0cHM6Ly9tLmFuanVrZS5jb20vY2QveGlhb3F1Lw%25253D%25253D; new_uv=15; new_session=0'

city_url = [
    {'city': '广州', 'url': 'https://m.anjuke.com/gz/xiaoqu/'},
    {'city': '成都', 'url': 'https://m.anjuke.com/cd/xiaoqu/'},
    {'city': '重庆', 'url': 'https://m.anjuke.com/cq/xiaoqu/'},
    {'city': '北京', 'url': 'https://m.anjuke.com/bj/xiaoqu/'},
    {'city': '上海', 'url': 'https://m.anjuke.com/sh/xiaoqu/'},
    {'city': '长沙', 'url': 'https://m.anjuke.com/cs/xiaoqu/'},
    {'city': '武汉', 'url': 'https://m.anjuke.com/wh/xiaoqu/'},
    {'city': '深圳', 'url': 'https://m.anjuke.com/sz/xiaoqu/'},
    {'city': '杭州', 'url': 'https://m.anjuke.com/hz/xiaoqu/'},
    {'city': '天津', 'url': 'https://m.anjuke.com/tj/xiaoqu/'},
    {'city': '鞍山', 'url': 'https://m.anjuke.com/as/xiaoqu/'},
    {'city': '安阳', 'url': 'https://m.anjuke.com/ay/xiaoqu/'},
    {'city': '安庆', 'url': 'https://m.anjuke.com/aq/xiaoqu/'},
    {'city': '安康', 'url': 'https://m.anjuke.com/ank/xiaoqu/'},
    {'city': '安顺', 'url': 'https://m.anjuke.com/ans/xiaoqu/'},
    {'city': '阿坝', 'url': 'https://m.anjuke.com/ab/xiaoqu/'},
    {'city': '阿克苏', 'url': 'https://m.anjuke.com/aks/xiaoqu/'},
    {'city': '阿里', 'url': 'https://m.anjuke.com/al/xiaoqu/'},
    {'city': '阿拉尔', 'url': 'https://m.anjuke.com/ale/xiaoqu/'},
    {'city': '阿拉善盟', 'url': 'https://m.anjuke.com/alsm/xiaoqu/'},
    {'city': '澳门', 'url': 'https://m.anjuke.com/am/xiaoqu/'},
    {'city': '安达', 'url': 'https://m.anjuke.com/ad/xiaoqu/'},
    {'city': '安丘', 'url': 'https://m.anjuke.com/anq/xiaoqu/'},
    {'city': '安宁', 'url': 'https://m.anjuke.com/ann/xiaoqu/'},
    {'city': '安国', 'url': 'https://m.anjuke.com/ang/xiaoqu/'},
    {'city': '阿尔山', 'url': 'https://m.anjuke.com/aesh/xiaoqu/'},
    {'city': '阿图什', 'url': 'https://m.anjuke.com/atsh/xiaoqu/'},
    {'city': '安陆', 'url': 'https://m.anjuke.com/anl/xiaoqu/'},

    {'city': '保定', 'url': 'https://m.anjuke.com/bd/xiaoqu/'},
    {'city': '包头', 'url': 'https://m.anjuke.com/bt/xiaoqu/'},
    {'city': '滨州', 'url': 'https://m.anjuke.com/bz/xiaoqu/'},
    {'city': '宝鸡', 'url': 'https://m.anjuke.com/bao/xiaoqu/'},
    {'city': '蚌埠', 'url': 'https://m.anjuke.com/bb/xiaoqu/'},
    {'city': '本溪', 'url': 'https://m.anjuke.com/bx/xiaoqu/'},
    {'city': '北海', 'url': 'https://m.anjuke.com/bh/xiaoqu/'},
    {'city': '巴音郭楞', 'url': 'https://m.anjuke.com/bygl/xiaoqu/'},
    {'city': '巴中', 'url': 'https://m.anjuke.com/ba/xiaoqu/'},
    {'city': '巴彦淖尔市', 'url': 'https://m.anjuke.com/bycem/xiaoqu/'},
    {'city': '亳州', 'url': 'https://m.anjuke.com/boz/xiaoqu/'},
    {'city': '白银', 'url': 'https://m.anjuke.com/by/xiaoqu/'},
    {'city': '白城', 'url': 'https://m.anjuke.com/bc/xiaoqu/'},
    {'city': '百色', 'url': 'https://m.anjuke.com/bais/xiaoqu/'},
    {'city': '白山', 'url': 'https://m.anjuke.com/baish/xiaoqu/'},
    {'city': '博尔塔拉', 'url': 'https://m.anjuke.com/betl/xiaoqu/'},
    {'city': '毕节', 'url': 'https://m.anjuke.com/bij/xiaoqu/'},
    {'city': '西双版纳', 'url': 'https://m.anjuke.com/bn/xiaoqu/'},
    {'city': '保山', 'url': 'https://m.anjuke.com/bs/xiaoqu/'},
    {'city': '霸州', 'url': 'https://m.anjuke.com/baz/xiaoqu/'},
    {'city': '北安', 'url': 'https://m.anjuke.com/ban/xiaoqu/'},
    {'city': '北票', 'url': 'https://m.anjuke.com/bp/xiaoqu/'},
    {'city': '泊头', 'url': 'https://m.anjuke.com/bot/xiaoqu/'},
    {'city': '博乐', 'url': 'https://m.anjuke.com/bl/xiaoqu/'},
    {'city': '北流', 'url': 'https://m.anjuke.com/beil/xiaoqu/'},

    {'city': '常州', 'url': 'https://m.anjuke.com/cz/xiaoqu/'},
    {'city': '长春', 'url': 'https://m.anjuke.com/cc/xiaoqu/'},
    {'city': '沧州', 'url': 'https://m.anjuke.com/cang/xiaoqu/'},
    {'city': '昌吉', 'url': 'https://m.anjuke.com/cj/xiaoqu/'},
    {'city': '赤峰', 'url': 'https://m.anjuke.com/cf/xiaoqu/'},
    {'city': '常德', 'url': 'https://m.anjuke.com/chd/xiaoqu/'},
    {'city': '郴州', 'url': 'https://m.anjuke.com/chen/xiaoqu/'},
    {'city': '承德', 'url': 'https://m.anjuke.com/cheng/xiaoqu/'},
    {'city': '长治', 'url': 'https://m.anjuke.com/chang/xiaoqu/'},
    {'city': '池州', 'url': 'https://m.anjuke.com/chi/xiaoqu/'},
    {'city': '滁州', 'url': 'https://m.anjuke.com/chu/xiaoqu/'},
    {'city': '朝阳', 'url': 'https://m.anjuke.com/cy/xiaoqu/'},
    {'city': '潮州', 'url': 'https://m.anjuke.com/chao/xiaoqu/'},
    {'city': '楚雄', 'url': 'https://m.anjuke.com/cx/xiaoqu/'},
    {'city': '巢湖', 'url': 'https://m.anjuke.com/ch/xiaoqu/'},
    {'city': '昌都', 'url': 'https://m.anjuke.com/changd/xiaoqu/'},
    {'city': '长葛', 'url': 'https://m.anjuke.com/cg/xiaoqu/'},
    {'city': '崇左', 'url': 'https://m.anjuke.com/chongz/xiaoqu/'},
    {'city': '常熟', 'url': 'https://m.anjuke.com/chss/xiaoqu/'},
    {'city': '昌邑', 'url': 'https://m.anjuke.com/chy/xiaoqu/'},
    {'city': '常宁', 'url': 'https://m.anjuke.com/chn/xiaoqu/'},
    {'city': '赤壁', 'url': 'https://m.anjuke.com/chb/xiaoqu/'},
    {'city': '岑溪', 'url': 'https://m.anjuke.com/cengx/xiaoqu/'},
    {'city': '赤水', 'url': 'https://m.anjuke.com/chish/xiaoqu/'},
    {'city': '慈溪', 'url': 'https://m.anjuke.com/cix/xiaoqu/'},
    {'city': '崇州', 'url': 'https://m.anjuke.com/chz/xiaoqu/'},
    {'city': '大连', 'url': 'https://m.anjuke.com/dl/xiaoqu/'},
    {'city': '东莞', 'url': 'https://m.anjuke.com/dg/xiaoqu/'},
    {'city': '德阳', 'url': 'https://m.anjuke.com/de/xiaoqu/'},
    {'city': '大理', 'url': 'https://m.anjuke.com/da/xiaoqu/'},
    {'city': '德州', 'url': 'https://m.anjuke.com/dz/xiaoqu/'},
    {'city': '东营', 'url': 'https://m.anjuke.com/dy/xiaoqu/'},
    {'city': '大庆', 'url': 'https://m.anjuke.com/dq/xiaoqu/'},
    {'city': '丹东', 'url': 'https://m.anjuke.com/dd/xiaoqu/'},
    {'city': '大同', 'url': 'https://m.anjuke.com/dt/xiaoqu/'},
    {'city': '达州', 'url': 'https://m.anjuke.com/dzh/xiaoqu/'},
    {'city': '大丰', 'url': 'https://m.anjuke.com/df/xiaoqu/'},
    {'city': '德宏', 'url': 'https://m.anjuke.com/dh/xiaoqu/'},
    {'city': '定州', 'url': 'https://m.anjuke.com/ding/xiaoqu/'},
    {'city': '迪庆', 'url': 'https://m.anjuke.com/diq/xiaoqu/'},
    {'city': '定西', 'url': 'https://m.anjuke.com/dx/xiaoqu/'},
    {'city': '大兴安岭', 'url': 'https://m.anjuke.com/dxal/xiaoqu/'},
    {'city': '东台', 'url': 'https://m.anjuke.com/dongt/xiaoqu/'},
    {'city': '邓州', 'url': 'https://m.anjuke.com/dengz/xiaoqu/'},
    {'city': '德惠', 'url': 'https://m.anjuke.com/dhu/xiaoqu/'},
    {'city': '当阳', 'url': 'https://m.anjuke.com/dongy/xiaoqu/'},
    {'city': '东方', 'url': 'https://m.anjuke.com/dfx/xiaoqu/'},
    {'city': '儋州', 'url': 'https://m.anjuke.com/danz/xiaoqu/'},
    {'city': '敦化', 'url': 'https://m.anjuke.com/dunhuashi/xiaoqu/'},
    {'city': '丹阳', 'url': 'https://m.anjuke.com/danyangshi/xiaoqu/'},
    {'city': '大石桥', 'url': 'https://m.anjuke.com/dshq/xiaoqu/'},
    {'city': '灯塔', 'url': 'https://m.anjuke.com/dengt/xiaoqu/'},
    {'city': '敦煌', 'url': 'https://m.anjuke.com/dunh/xiaoqu/'},
    {'city': '德令哈', 'url': 'https://m.anjuke.com/dlh/xiaoqu/'},
    {'city': '大冶', 'url': 'https://m.anjuke.com/day/xiaoqu/'},
    {'city': '都匀', 'url': 'https://m.anjuke.com/duy/xiaoqu/'},
    {'city': '东兴', 'url': 'https://m.anjuke.com/dongx/xiaoqu/'},
    {'city': '东阳', 'url': 'https://m.anjuke.com/dongyang/xiaoqu/'},
    {'city': '德兴', 'url': 'https://m.anjuke.com/dex/xiaoqu/'},
    {'city': '丹江口', 'url': 'https://m.anjuke.com/djk/xiaoqu/'},
    {'city': '都江堰', 'url': 'https://m.anjuke.com/djy/xiaoqu/'},
    {'city': '东港', 'url': 'https://m.anjuke.com/dongg/xiaoqu/'},
    {'city': '登封', 'url': 'https://m.anjuke.com/def/xiaoqu/'},
    {'city': '鄂尔多斯', 'url': 'https://m.anjuke.com/eeds/xiaoqu/'},
    {'city': '恩施', 'url': 'https://m.anjuke.com/es/xiaoqu/'},
    {'city': '鄂州', 'url': 'https://m.anjuke.com/ez/xiaoqu/'},
    {'city': '恩平', 'url': 'https://m.anjuke.com/ep/xiaoqu/'},
    {'city': '峨眉山', 'url': 'https://m.anjuke.com/ems/xiaoqu/'},
    {'city': '佛山', 'url': 'https://m.anjuke.com/fs/xiaoqu/'},
    {'city': '福州', 'url': 'https://m.anjuke.com/fz/xiaoqu/'},
    {'city': '阜阳', 'url': 'https://m.anjuke.com/fy/xiaoqu/'},
    {'city': '抚顺', 'url': 'https://m.anjuke.com/fsh/xiaoqu/'},
    {'city': '阜新', 'url': 'https://m.anjuke.com/fx/xiaoqu/'},
    {'city': '抚州', 'url': 'https://m.anjuke.com/fuz/xiaoqu/'},
    {'city': '防城港', 'url': 'https://m.anjuke.com/fcg/xiaoqu/'},
    {'city': '肥城', 'url': 'https://m.anjuke.com/fcs/xiaoqu/'},
    {'city': '丰城', 'url': 'https://m.anjuke.com/fengc/xiaoqu/'},
    {'city': '丰镇', 'url': 'https://m.anjuke.com/fzh/xiaoqu/'},
    {'city': '汾阳', 'url': 'https://m.anjuke.com/feny/xiaoqu/'},
    {'city': '阜康', 'url': 'https://m.anjuke.com/fuk/xiaoqu/'},
    {'city': '福泉', 'url': 'https://m.anjuke.com/fuq/xiaoqu/'},
    {'city': '福清', 'url': 'https://m.anjuke.com/fq/xiaoqu/'},
    {'city': '福安', 'url': 'https://m.anjuke.com/fa/xiaoqu/'},
    {'city': '凤城', 'url': 'https://m.anjuke.com/fc/xiaoqu/'},
    {'city': '福鼎', 'url': 'https://m.anjuke.com/fding/xiaoqu/'},

    {'city': '贵阳', 'url': 'https://m.anjuke.com/gy/xiaoqu/'},
    {'city': '桂林', 'url': 'https://m.anjuke.com/gl/xiaoqu/'},
    {'city': '赣州', 'url': 'https://m.anjuke.com/gan/xiaoqu/'},
    {'city': '广安', 'url': 'https://m.anjuke.com/ga/xiaoqu/'},
    {'city': '贵港', 'url': 'https://m.anjuke.com/gg/xiaoqu/'},
    {'city': '广元', 'url': 'https://m.anjuke.com/guang/xiaoqu/'},
    {'city': '甘孜', 'url': 'https://m.anjuke.com/gaz/xiaoqu/'},
    {'city': '甘南', 'url': 'https://m.anjuke.com/gn/xiaoqu/'},
    {'city': '馆陶', 'url': 'https://m.anjuke.com/gt/xiaoqu/'},
    {'city': '果洛', 'url': 'https://m.anjuke.com/guo/xiaoqu/'},
    {'city': '固原', 'url': 'https://m.anjuke.com/gu/xiaoqu/'},
    {'city': '公主岭', 'url': 'https://m.anjuke.com/gzls/xiaoqu/'},
    {'city': '高邮', 'url': 'https://m.anjuke.com/gay/xiaoqu/'},
    {'city': '高密', 'url': 'https://m.anjuke.com/gms/xiaoqu/'},
    {'city': '广水', 'url': 'https://m.anjuke.com/gsh/xiaoqu/'},
    {'city': '盖州', 'url': 'https://m.anjuke.com/gaizh/xiaoqu/'},
    {'city': '格尔木', 'url': 'https://m.anjuke.com/gem/xiaoqu/'},
    {'city': '广汉', 'url': 'https://m.anjuke.com/gh/xiaoqu/'},
    {'city': '个旧', 'url': 'https://m.anjuke.com/gj/xiaoqu/'},
    {'city': '桂平', 'url': 'https://m.anjuke.com/gp/xiaoqu/'},
    {'city': '贵溪', 'url': 'https://m.anjuke.com/gx/xiaoqu/'},
    {'city': '高安', 'url': 'https://m.anjuke.com/gaoanshi/xiaoqu/'},
    {'city': '高州', 'url': 'https://m.anjuke.com/gaozh/xiaoqu/'},
    {'city': '高要', 'url': 'https://m.anjuke.com/gaoyaoshi/xiaoqu/'},
    {'city': '古交', 'url': 'https://m.anjuke.com/guj/xiaoqu/'},
    {'city': '高碑店', 'url': 'https://m.anjuke.com/gbd/xiaoqu/'},
    {'city': '香港', 'url': 'https://m.anjuke.com/hongkong/xiaoqu/'},
    {'city': '合肥', 'url': 'https://m.anjuke.com/hf/xiaoqu/'},
    {'city': '哈尔滨', 'url': 'https://m.anjuke.com/heb/xiaoqu/'},
    {'city': '海口', 'url': 'https://m.anjuke.com/hai/xiaoqu/'},
    {'city': '惠州', 'url': 'https://m.anjuke.com/hui/xiaoqu/'},
    {'city': '邯郸', 'url': 'https://m.anjuke.com/hd/xiaoqu/'},
    {'city': '呼和浩特', 'url': 'https://m.anjuke.com/hhht/xiaoqu/'},
    {'city': '黄冈', 'url': 'https://m.anjuke.com/hg/xiaoqu/'},
    {'city': '淮南', 'url': 'https://m.anjuke.com/hn/xiaoqu/'},
    {'city': '黄山', 'url': 'https://m.anjuke.com/hsh/xiaoqu/'},
    {'city': '鹤壁', 'url': 'https://m.anjuke.com/hb/xiaoqu/'},
    {'city': '衡阳', 'url': 'https://m.anjuke.com/hy/xiaoqu/'},
    {'city': '湖州', 'url': 'https://m.anjuke.com/hu/xiaoqu/'},
    {'city': '衡水', 'url': 'https://m.anjuke.com/hs/xiaoqu/'},
    {'city': '汉中', 'url': 'https://m.anjuke.com/han/xiaoqu/'},
    {'city': '淮安', 'url': 'https://m.anjuke.com/ha/xiaoqu/'},
    {'city': '黄石', 'url': 'https://m.anjuke.com/huang/xiaoqu/'},
    {'city': '菏泽', 'url': 'https://m.anjuke.com/hez/xiaoqu/'},
    {'city': '怀化', 'url': 'https://m.anjuke.com/hh/xiaoqu/'},
    {'city': '淮北', 'url': 'https://m.anjuke.com/huai/xiaoqu/'},
    {'city': '葫芦岛', 'url': 'https://m.anjuke.com/hld/xiaoqu/'},
    {'city': '河源', 'url': 'https://m.anjuke.com/he/xiaoqu/'},
    {'city': '红河', 'url': 'https://m.anjuke.com/hong/xiaoqu/'},
    {'city': '哈密', 'url': 'https://m.anjuke.com/hami/xiaoqu/'},
    {'city': '鹤岗', 'url': 'https://m.anjuke.com/heg/xiaoqu/'},
    {'city': '呼伦贝尔', 'url': 'https://m.anjuke.com/hlbe/xiaoqu/'},
    {'city': '海北', 'url': 'https://m.anjuke.com/haib/xiaoqu/'},
    {'city': '海东', 'url': 'https://m.anjuke.com/haid/xiaoqu/'},
    {'city': '海南', 'url': 'https://m.anjuke.com/hain/xiaoqu/'},
    {'city': '河池', 'url': 'https://m.anjuke.com/hc/xiaoqu/'},
    {'city': '黑河', 'url': 'https://m.anjuke.com/heih/xiaoqu/'},
    {'city': '和县', 'url': 'https://m.anjuke.com/hex/xiaoqu/'},
    {'city': '贺州', 'url': 'https://m.anjuke.com/hezh/xiaoqu/'},
    {'city': '海拉尔', 'url': 'https://m.anjuke.com/hlr/xiaoqu/'},
    {'city': '霍邱', 'url': 'https://m.anjuke.com/hq/xiaoqu/'},
    {'city': '和田', 'url': 'https://m.anjuke.com/ht/xiaoqu/'},
    {'city': '黄南', 'url': 'https://m.anjuke.com/huangn/xiaoqu/'},
    {'city': '海西', 'url': 'https://m.anjuke.com/hx/xiaoqu/'},
    {'city': '桦甸', 'url': 'https://m.anjuke.com/hid/xiaoqu/'},
    {'city': '鹤山', 'url': 'https://m.anjuke.com/hesh/xiaoqu/'},
    {'city': '海林', 'url': 'https://m.anjuke.com/hl/xiaoqu/'},
    {'city': '海城', 'url': 'https://m.anjuke.com/hic/xiaoqu/'},
    {'city': '珲春', 'url': 'https://m.anjuke.com/hunc/xiaoqu/'},
    {'city': '黄骅', 'url': 'https://m.anjuke.com/huangh/xiaoqu/'},
    {'city': '河间', 'url': 'https://m.anjuke.com/hj/xiaoqu/'},
    {'city': '韩城', 'url': 'https://m.anjuke.com/hanch/xiaoqu/'},
    {'city': '华阴', 'url': 'https://m.anjuke.com/huaying/xiaoqu/'},
    {'city': '侯马', 'url': 'https://m.anjuke.com/houm/xiaoqu/'},
    {'city': '华蓥', 'url': 'https://m.anjuke.com/huay/xiaoqu/'},
    {'city': '合山', 'url': 'https://m.anjuke.com/heshshi/xiaoqu/'},
    {'city': '辉县', 'url': 'https://m.anjuke.com/huix/xiaoqu/'},
    {'city': '化州', 'url': 'https://m.anjuke.com/huazh/xiaoqu/'},
    {'city': '霍州', 'url': 'https://m.anjuke.com/huozh/xiaoqu/'},
    {'city': '洪湖', 'url': 'https://m.anjuke.com/hongh/xiaoqu/'},
    {'city': '洪江', 'url': 'https://m.anjuke.com/hongj/xiaoqu/'},
    {'city': '和龙', 'url': 'https://m.anjuke.com/hel/xiaoqu/'},
    {'city': '海门', 'url': 'https://m.anjuke.com/hm/xiaoqu/'},
    {'city': '海宁', 'url': 'https://m.anjuke.com/haining/xiaoqu/'},
    {'city': '海阳', 'url': 'https://m.anjuke.com/haiy/xiaoqu/'},
    {'city': '济南', 'url': 'https://m.anjuke.com/jn/xiaoqu/'},
    {'city': '嘉兴', 'url': 'https://m.anjuke.com/jx/xiaoqu/'},
    {'city': '吉林', 'url': 'https://m.anjuke.com/jl/xiaoqu/'},
    {'city': '江门', 'url': 'https://m.anjuke.com/jm/xiaoqu/'},
    {'city': '荆门', 'url': 'https://m.anjuke.com/jing/xiaoqu/'},
    {'city': '锦州', 'url': 'https://m.anjuke.com/jz/xiaoqu/'},
    {'city': '景德镇', 'url': 'https://m.anjuke.com/jdz/xiaoqu/'},
    {'city': '吉安', 'url': 'https://m.anjuke.com/ja/xiaoqu/'},
    {'city': '济宁', 'url': 'https://m.anjuke.com/ji/xiaoqu/'},
    {'city': '金华', 'url': 'https://m.anjuke.com/jh/xiaoqu/'},
    {'city': '揭阳', 'url': 'https://m.anjuke.com/jy/xiaoqu/'},
    {'city': '晋中', 'url': 'https://m.anjuke.com/jin/xiaoqu/'},
    {'city': '九江', 'url': 'https://m.anjuke.com/jj/xiaoqu/'},
    {'city': '焦作', 'url': 'https://m.anjuke.com/jiao/xiaoqu/'},
    {'city': '晋城', 'url': 'https://m.anjuke.com/jc/xiaoqu/'},
    {'city': '荆州', 'url': 'https://m.anjuke.com/jzh/xiaoqu/'},
    {'city': '佳木斯', 'url': 'https://m.anjuke.com/jms/xiaoqu/'},
    {'city': '酒泉', 'url': 'https://m.anjuke.com/jq/xiaoqu/'},
    {'city': '鸡西', 'url': 'https://m.anjuke.com/jixi/xiaoqu/'},
    {'city': '济源', 'url': 'https://m.anjuke.com/jiy/xiaoqu/'},
    {'city': '金昌', 'url': 'https://m.anjuke.com/jinc/xiaoqu/'},
    {'city': '嘉峪关', 'url': 'https://m.anjuke.com/jyg/xiaoqu/'},
    {'city': '江阴', 'url': 'https://m.anjuke.com/jiangy/xiaoqu/'},
    {'city': '靖江', 'url': 'https://m.anjuke.com/jingj/xiaoqu/'},
    {'city': '简阳', 'url': 'https://m.anjuke.com/jys/xiaoqu/'},
    {'city': '金坛', 'url': 'https://m.anjuke.com/jint/xiaoqu/'},
    {'city': '津市', 'url': 'https://m.anjuke.com/js/xiaoqu/'},
    {'city': '界首', 'url': 'https://m.anjuke.com/jiesh/xiaoqu/'},
    {'city': '吉首', 'url': 'https://m.anjuke.com/jish/xiaoqu/'},
    {'city': '景洪', 'url': 'https://m.anjuke.com/jingh/xiaoqu/'},
    {'city': '晋江', 'url': 'https://m.anjuke.com/jinjiangs/xiaoqu/'},
    {'city': '建瓯', 'url': 'https://m.anjuke.com/jou/xiaoqu/'},
    {'city': '江山', 'url': 'https://m.anjuke.com/jiangsh/xiaoqu/'},
    {'city': '井冈山', 'url': 'https://m.anjuke.com/jgsh/xiaoqu/'},
    {'city': '蛟河', 'url': 'https://m.anjuke.com/jiaoh/xiaoqu/'},
    {'city': '胶州', 'url': 'https://m.anjuke.com/jzhx/xiaoqu/'},
    {'city': '句容', 'url': 'https://m.anjuke.com/jr/xiaoqu/'},
    {'city': '建德', 'url': 'https://m.anjuke.com/jde/xiaoqu/'},
    {'city': '冀州', 'url': 'https://m.anjuke.com/jiz/xiaoqu/'},
    {'city': '江油市', 'url': 'https://m.anjuke.com/jyou/xiaoqu/'},
    {'city': '昆明', 'url': 'https://m.anjuke.com/km/xiaoqu/'},
    {'city': '昆山', 'url': 'https://m.anjuke.com/ks/xiaoqu/'},
    {'city': '开封', 'url': 'https://m.anjuke.com/kf/xiaoqu/'},
    {'city': '喀什', 'url': 'https://m.anjuke.com/ka/xiaoqu/'},
    {'city': '克拉玛依', 'url': 'https://m.anjuke.com/klmy/xiaoqu/'},
    {'city': '垦利', 'url': 'https://m.anjuke.com/kl/xiaoqu/'},
    {'city': '库尔勒', 'url': 'https://m.anjuke.com/kelx/xiaoqu/'},
    {'city': '奎屯', 'url': 'https://m.anjuke.com/kt/xiaoqu/'},
    {'city': '凯里', 'url': 'https://m.anjuke.com/kli/xiaoqu/'},
    {'city': '开平', 'url': 'https://m.anjuke.com/kp/xiaoqu/'},
    {'city': '开原', 'url': 'https://m.anjuke.com/kaiyuan/xiaoqu/'},
    {'city': '开远', 'url': 'https://m.anjuke.com/kaiy/xiaoqu/'},
    {'city': '兰州', 'url': 'https://m.anjuke.com/lz/xiaoqu/'},
    {'city': '廊坊', 'url': 'https://m.anjuke.com/lf/xiaoqu/'},
    {'city': '洛阳', 'url': 'https://m.anjuke.com/ly/xiaoqu/'},
    {'city': '柳州', 'url': 'https://m.anjuke.com/lzh/xiaoqu/'},
    {'city': '莱芜', 'url': 'https://m.anjuke.com/lw/xiaoqu/'},
    {'city': '六安', 'url': 'https://m.anjuke.com/la/xiaoqu/'},
    {'city': '泸州', 'url': 'https://m.anjuke.com/lu/xiaoqu/'},
    {'city': '丽江', 'url': 'https://m.anjuke.com/lj/xiaoqu/'},
    {'city': '临沂', 'url': 'https://m.anjuke.com/liny/xiaoqu/'},
    {'city': '聊城', 'url': 'https://m.anjuke.com/lc/xiaoqu/'},
    {'city': '连云港', 'url': 'https://m.anjuke.com/lyg/xiaoqu/'},
    {'city': '丽水', 'url': 'https://m.anjuke.com/li/xiaoqu/'},
    {'city': '娄底', 'url': 'https://m.anjuke.com/ld/xiaoqu/'},
    {'city': '乐山', 'url': 'https://m.anjuke.com/le/xiaoqu/'},
    {'city': '辽阳', 'url': 'https://m.anjuke.com/liao/xiaoqu/'},
    {'city': '拉萨', 'url': 'https://m.anjuke.com/ls/xiaoqu/'},
    {'city': '临汾', 'url': 'https://m.anjuke.com/lin/xiaoqu/'},
    {'city': '龙岩', 'url': 'https://m.anjuke.com/long/xiaoqu/'},
    {'city': '漯河', 'url': 'https://m.anjuke.com/lh/xiaoqu/'},
    {'city': '凉山', 'url': 'https://m.anjuke.com/liang/xiaoqu/'},
    {'city': '六盘水', 'url': 'https://m.anjuke.com/lps/xiaoqu/'},
    {'city': '辽源', 'url': 'https://m.anjuke.com/liaoy/xiaoqu/'},
    {'city': '克孜勒苏', 'url': 'https://m.anjuke.com/kzls/xiaoqu/'},
    {'city': '来宾', 'url': 'https://m.anjuke.com/lb/xiaoqu/'},
    {'city': '临沧', 'url': 'https://m.anjuke.com/linc/xiaoqu/'},
    {'city': '临夏', 'url': 'https://m.anjuke.com/lx/xiaoqu/'},
    {'city': '临猗', 'url': 'https://m.anjuke.com/linyis/xiaoqu/'},
    {'city': '林芝', 'url': 'https://m.anjuke.com/lizh/xiaoqu/'},
    {'city': '陇南', 'url': 'https://m.anjuke.com/ln/xiaoqu/'},
    {'city': '吕梁', 'url': 'https://m.anjuke.com/lvl/xiaoqu/'},
    {'city': '临海', 'url': 'https://m.anjuke.com/lihs/xiaoqu/'},
    {'city': '龙海', 'url': 'https://m.anjuke.com/lhs/xiaoqu/'},
    {'city': '醴陵', 'url': 'https://m.anjuke.com/lls/xiaoqu/'},
    {'city': '临清', 'url': 'https://m.anjuke.com/linq/xiaoqu/'},
    {'city': '龙口', 'url': 'https://m.anjuke.com/lk/xiaoqu/'},
    {'city': '莱阳', 'url': 'https://m.anjuke.com/lay/xiaoqu/'},
    {'city': '耒阳', 'url': 'https://m.anjuke.com/leiy/xiaoqu/'},
    {'city': '溧阳', 'url': 'https://m.anjuke.com/liy/xiaoqu/'},
    {'city': '龙井', 'url': 'https://m.anjuke.com/lg/xiaoqu/'},
    {'city': '临江', 'url': 'https://m.anjuke.com/lingj/xiaoqu/'},
    {'city': '凌源', 'url': 'https://m.anjuke.com/lingy/xiaoqu/'},
    {'city': '林州', 'url': 'https://m.anjuke.com/linzhoushi/xiaoqu/'},
    {'city': '灵宝', 'url': 'https://m.anjuke.com/lingb/xiaoqu/'},
    {'city': '潞城', 'url': 'https://m.anjuke.com/luch/xiaoqu/'},
    {'city': '利川', 'url': 'https://m.anjuke.com/lich/xiaoqu/'},
    {'city': '冷水江', 'url': 'https://m.anjuke.com/lshj/xiaoqu/'},
    {'city': '涟源', 'url': 'https://m.anjuke.com/liany/xiaoqu/'},
    {'city': '阆中', 'url': 'https://m.anjuke.com/langzh/xiaoqu/'},
    {'city': '潞西', 'url': 'https://m.anjuke.com/luxishi/xiaoqu/'},
    {'city': '兰溪', 'url': 'https://m.anjuke.com/lanx/xiaoqu/'},
    {'city': '乐昌', 'url': 'https://m.anjuke.com/lech/xiaoqu/'},
    {'city': '廉江', 'url': 'https://m.anjuke.com/lianjiangshi/xiaoqu/'},
    {'city': '雷州', 'url': 'https://m.anjuke.com/leizh/xiaoqu/'},
    {'city': '陆丰', 'url': 'https://m.anjuke.com/lufengshi/xiaoqu/'},
    {'city': '连州', 'url': 'https://m.anjuke.com/lianzh/xiaoqu/'},
    {'city': '罗定', 'url': 'https://m.anjuke.com/luod/xiaoqu/'},
    {'city': '临湘', 'url': 'https://m.anjuke.com/lingx/xiaoqu/'},
    {'city': '龙泉', 'url': 'https://m.anjuke.com/longq/xiaoqu/'},
    {'city': '乐平', 'url': 'https://m.anjuke.com/lp/xiaoqu/'},
    {'city': '乐陵', 'url': 'https://m.anjuke.com/laol/xiaoqu/'},
    {'city': '莱州', 'url': 'https://m.anjuke.com/lzs/xiaoqu/'},
    {'city': '浏阳', 'url': 'https://m.anjuke.com/liuy/xiaoqu/'},
    {'city': '老河口', 'url': 'https://m.anjuke.com/lhk/xiaoqu/'},
    {'city': '莱西', 'url': 'https://m.anjuke.com/lai/xiaoqu/'},
    {'city': '绵阳', 'url': 'https://m.anjuke.com/my/xiaoqu/'},
    {'city': '茂名', 'url': 'https://m.anjuke.com/mm/xiaoqu/'},
    {'city': '马鞍山', 'url': 'https://m.anjuke.com/mas/xiaoqu/'},
    {'city': '牡丹江', 'url': 'https://m.anjuke.com/mdj/xiaoqu/'},
    {'city': '眉山', 'url': 'https://m.anjuke.com/ms/xiaoqu/'},
    {'city': '梅州', 'url': 'https://m.anjuke.com/mz/xiaoqu/'},
    {'city': '明港', 'url': 'https://m.anjuke.com/mg/xiaoqu/'},
    {'city': '密山', 'url': 'https://m.anjuke.com/msh/xiaoqu/'},
    {'city': '梅河口', 'url': 'https://m.anjuke.com/mhk/xiaoqu/'},
    {'city': '满洲里', 'url': 'https://m.anjuke.com/mzhl/xiaoqu/'},
    {'city': '孟州', 'url': 'https://m.anjuke.com/mzh/xiaoqu/'},
    {'city': '麻城', 'url': 'https://m.anjuke.com/mch/xiaoqu/'},
    {'city': '绵竹', 'url': 'https://m.anjuke.com/mianzh/xiaoqu/'},
    {'city': '明光', 'url': 'https://m.anjuke.com/mingg/xiaoqu/'},
    {'city': '汨罗', 'url': 'https://m.anjuke.com/mil/xiaoqu/'},
    {'city': '南京', 'url': 'https://m.anjuke.com/nj/xiaoqu/'},
    {'city': '宁波', 'url': 'https://m.anjuke.com/nb/xiaoqu/'},
    {'city': '南昌', 'url': 'https://m.anjuke.com/nc/xiaoqu/'},
    {'city': '南宁', 'url': 'https://m.anjuke.com/nn/xiaoqu/'},
    {'city': '南通', 'url': 'https://m.anjuke.com/nt/xiaoqu/'},
    {'city': '南充', 'url': 'https://m.anjuke.com/nan/xiaoqu/'},
    {'city': '南阳', 'url': 'https://m.anjuke.com/ny/xiaoqu/'},
    {'city': '宁德', 'url': 'https://m.anjuke.com/nd/xiaoqu/'},
    {'city': '内江', 'url': 'https://m.anjuke.com/nei/xiaoqu/'},
    {'city': '南平', 'url': 'https://m.anjuke.com/np/xiaoqu/'},
    {'city': '那曲', 'url': 'https://m.anjuke.com/nq/xiaoqu/'},
    {'city': '怒江', 'url': 'https://m.anjuke.com/nu/xiaoqu/'},
    {'city': '南安', 'url': 'https://m.anjuke.com/na/xiaoqu/'},
    {'city': '宁安', 'url': 'https://m.anjuke.com/ninganshi/xiaoqu/'},
    {'city': '宁国', 'url': 'https://m.anjuke.com/ningg/xiaoqu/'},
    {'city': '南康', 'url': 'https://m.anjuke.com/nk/xiaoqu/'},
    {'city': '南雄', 'url': 'https://m.anjuke.com/nanx/xiaoqu/'},
    {'city': '讷河', 'url': 'https://m.anjuke.com/neh/xiaoqu/'},
    {'city': '南宫', 'url': 'https://m.anjuke.com/ngong/xiaoqu/'},
    {'city': '攀枝花', 'url': 'https://m.anjuke.com/pzh/xiaoqu/'},
    {'city': '平顶山', 'url': 'https://m.anjuke.com/pds/xiaoqu/'},
    {'city': '盘锦', 'url': 'https://m.anjuke.com/pj/xiaoqu/'},
    {'city': '萍乡', 'url': 'https://m.anjuke.com/px/xiaoqu/'},
    {'city': '濮阳', 'url': 'https://m.anjuke.com/py/xiaoqu/'},
    {'city': '莆田', 'url': 'https://m.anjuke.com/pt/xiaoqu/'},
    {'city': '普洱', 'url': 'https://m.anjuke.com/pe/xiaoqu/'},
    {'city': '平凉', 'url': 'https://m.anjuke.com/pl/xiaoqu/'},
    {'city': '普宁', 'url': 'https://m.anjuke.com/pn/xiaoqu/'},
    {'city': '普兰店', 'url': 'https://m.anjuke.com/puld/xiaoqu/'},
    {'city': '凭祥', 'url': 'https://m.anjuke.com/pingxiang/xiaoqu/'},
    {'city': '邳州', 'url': 'https://m.anjuke.com/piz/xiaoqu/'},
    {'city': '蓬莱', 'url': 'https://m.anjuke.com/pls/xiaoqu/'},
    {'city': '平湖', 'url': 'https://m.anjuke.com/ph/xiaoqu/'},
    {'city': '平度', 'url': 'https://m.anjuke.com/pd/xiaoqu/'},
    {'city': '彭州', 'url': 'https://m.anjuke.com/pz/xiaoqu/'},
    {'city': '青岛', 'url': 'https://m.anjuke.com/qd/xiaoqu/'},
    {'city': '秦皇岛', 'url': 'https://m.anjuke.com/qhd/xiaoqu/'},
    {'city': '泉州', 'url': 'https://m.anjuke.com/qz/xiaoqu/'},
    {'city': '曲靖', 'url': 'https://m.anjuke.com/qj/xiaoqu/'},
    {'city': '齐齐哈尔', 'url': 'https://m.anjuke.com/qqhe/xiaoqu/'},
    {'city': '衢州', 'url': 'https://m.anjuke.com/qu/xiaoqu/'},
    {'city': '清远', 'url': 'https://m.anjuke.com/qy/xiaoqu/'},
    {'city': '钦州', 'url': 'https://m.anjuke.com/qin/xiaoqu/'},
    {'city': '庆阳', 'url': 'https://m.anjuke.com/qing/xiaoqu/'},
    {'city': '黔东南', 'url': 'https://m.anjuke.com/qdn/xiaoqu/'},
    {'city': '潜江', 'url': 'https://m.anjuke.com/qian/xiaoqu/'},
    {'city': '清徐', 'url': 'https://m.anjuke.com/qx/xiaoqu/'},
    {'city': '黔南', 'url': 'https://m.anjuke.com/qn/xiaoqu/'},
    {'city': '七台河', 'url': 'https://m.anjuke.com/qth/xiaoqu/'},
    {'city': '黔西南', 'url': 'https://m.anjuke.com/qxn/xiaoqu/'},
    {'city': '迁安', 'url': 'https://m.anjuke.com/qns/xiaoqu/'},
    {'city': '青州', 'url': 'https://m.anjuke.com/qzs/xiaoqu/'},
    {'city': '清镇', 'url': 'https://m.anjuke.com/qzh/xiaoqu/'},
    {'city': '琼海', 'url': 'https://m.anjuke.com/qh/xiaoqu/'},
    {'city': '青铜峡', 'url': 'https://m.anjuke.com/qtx/xiaoqu/'},
    {'city': '沁阳', 'url': 'https://m.anjuke.com/qinyangshi/xiaoqu/'},
    {'city': '曲阜', 'url': 'https://m.anjuke.com/qf/xiaoqu/'},
    {'city': '邛崃', 'url': 'https://m.anjuke.com/ql/xiaoqu/'},
    {'city': '启东', 'url': 'https://m.anjuke.com/qid/xiaoqu/'},
    {'city': '日照', 'url': 'https://m.anjuke.com/rz/xiaoqu/'},
    {'city': '日喀则', 'url': 'https://m.anjuke.com/rkz/xiaoqu/'},
    {'city': '瑞安', 'url': 'https://m.anjuke.com/ra/xiaoqu/'},
    {'city': '汝州', 'url': 'https://m.anjuke.com/rzs/xiaoqu/'},
    {'city': '任丘', 'url': 'https://m.anjuke.com/rqs/xiaoqu/'},
    {'city': '瑞金', 'url': 'https://m.anjuke.com/rj/xiaoqu/'},
    {'city': '乳山', 'url': 'https://m.anjuke.com/rsh/xiaoqu/'},
    {'city': '仁怀', 'url': 'https://m.anjuke.com/rh/xiaoqu/'},
    {'city': '瑞昌', 'url': 'https://m.anjuke.com/rch/xiaoqu/'},
    {'city': '瑞丽', 'url': 'https://m.anjuke.com/rl/xiaoqu/'},
    {'city': '如皋', 'url': 'https://m.anjuke.com/rg/xiaoqu/'},
    {'city': '荣成市', 'url': 'https://m.anjuke.com/rcheng/xiaoqu/'},

    {'city': '苏州', 'url': 'https://m.anjuke.com/su/xiaoqu/'},
    {'city': '石家庄', 'url': 'https://m.anjuke.com/sjz/xiaoqu/'},
    {'city': '沈阳', 'url': 'https://m.anjuke.com/shen/xiaoqu/'},
    {'city': '三亚', 'url': 'https://m.anjuke.com/sy/xiaoqu/'},
    {'city': '绍兴', 'url': 'https://m.anjuke.com/sx/xiaoqu/'},
    {'city': '汕头', 'url': 'https://m.anjuke.com/st/xiaoqu/'},
    {'city': '十堰', 'url': 'https://m.anjuke.com/shi/xiaoqu/'},
    {'city': '三门峡', 'url': 'https://m.anjuke.com/smx/xiaoqu/'},
    {'city': '三明', 'url': 'https://m.anjuke.com/sm/xiaoqu/'},
    {'city': '韶关', 'url': 'https://m.anjuke.com/sg/xiaoqu/'},
    {'city': '商丘', 'url': 'https://m.anjuke.com/sq/xiaoqu/'},
    {'city': '宿迁', 'url': 'https://m.anjuke.com/suq/xiaoqu/'},
    {'city': '绥化', 'url': 'https://m.anjuke.com/sui/xiaoqu/'},
    {'city': '邵阳', 'url': 'https://m.anjuke.com/shao/xiaoqu/'},
    {'city': '遂宁', 'url': 'https://m.anjuke.com/sn/xiaoqu/'},
    {'city': '上饶', 'url': 'https://m.anjuke.com/sr/xiaoqu/'},
    {'city': '四平', 'url': 'https://m.anjuke.com/sip/xiaoqu/'},
    {'city': '石河子', 'url': 'https://m.anjuke.com/shz/xiaoqu/'},
    {'city': '顺德', 'url': 'https://m.anjuke.com/sd/xiaoqu/'},
    {'city': '宿州', 'url': 'https://m.anjuke.com/suz/xiaoqu/'},
    {'city': '松原', 'url': 'https://m.anjuke.com/song/xiaoqu/'},
    {'city': '沭阳', 'url': 'https://m.anjuke.com/shuy/xiaoqu/'},
    {'city': '石嘴山', 'url': 'https://m.anjuke.com/szs/xiaoqu/'},
    {'city': '随州', 'url': 'https://m.anjuke.com/suiz/xiaoqu/'},
    {'city': '朔州', 'url': 'https://m.anjuke.com/shuo/xiaoqu/'},
    {'city': '汕尾', 'url': 'https://m.anjuke.com/sw/xiaoqu/'},
    {'city': '三沙', 'url': 'https://m.anjuke.com/sansh/xiaoqu/'},
    {'city': '商洛', 'url': 'https://m.anjuke.com/sl/xiaoqu/'},
    {'city': '山南', 'url': 'https://m.anjuke.com/shn/xiaoqu/'},
    {'city': '神农架', 'url': 'https://m.anjuke.com/snj/xiaoqu/'},
    {'city': '双鸭山', 'url': 'https://m.anjuke.com/sys/xiaoqu/'},
    {'city': '石狮', 'url': 'https://m.anjuke.com/shis/xiaoqu/'},
    {'city': '三河', 'url': 'https://m.anjuke.com/shs/xiaoqu/'},
    {'city': '尚志', 'url': 'https://m.anjuke.com/szhi/xiaoqu/'},
    {'city': '寿光', 'url': 'https://m.anjuke.com/shg/xiaoqu/'},
    {'city': '嵊州', 'url': 'https://m.anjuke.com/shzhou/xiaoqu/'},
    {'city': '绥芬河', 'url': 'https://m.anjuke.com/sfh/xiaoqu/'},
    {'city': '什邡', 'url': 'https://m.anjuke.com/shf/xiaoqu/'},
    {'city': '四会', 'url': 'https://m.anjuke.com/sih/xiaoqu/'},
    {'city': '邵武', 'url': 'https://m.anjuke.com/shw/xiaoqu/'},
    {'city': '松滋', 'url': 'https://m.anjuke.com/songz/xiaoqu/'},
    {'city': '石首', 'url': 'https://m.anjuke.com/shsh/xiaoqu/'},
    {'city': '韶山', 'url': 'https://m.anjuke.com/shaosh/xiaoqu/'},
    {'city': '深州', 'url': 'https://m.anjuke.com/szh/xiaoqu/'},
    {'city': '沙河', 'url': 'https://m.anjuke.com/shaheshi/xiaoqu/'},

    {'city': '太原', 'url': 'https://m.anjuke.com/ty/xiaoqu/'},
    {'city': '泰州', 'url': 'https://m.anjuke.com/tz/xiaoqu/'},
    {'city': '唐山', 'url': 'https://m.anjuke.com/ts/xiaoqu/'},
    {'city': '泰安', 'url': 'https://m.anjuke.com/ta/xiaoqu/'},
    {'city': '台州', 'url': 'https://m.anjuke.com/tai/xiaoqu/'},
    {'city': '铁岭', 'url': 'https://m.anjuke.com/tl/xiaoqu/'},
    {'city': '通辽', 'url': 'https://m.anjuke.com/tongl/xiaoqu/'},
    {'city': '铜陵', 'url': 'https://m.anjuke.com/tong/xiaoqu/'},
    {'city': '天水', 'url': 'https://m.anjuke.com/tian/xiaoqu/'},
    {'city': '通化', 'url': 'https://m.anjuke.com/th/xiaoqu/'},
    {'city': '台山', 'url': 'https://m.anjuke.com/taish/xiaoqu/'},
    {'city': '铜川', 'url': 'https://m.anjuke.com/tc/xiaoqu/'},
    {'city': '吐鲁番', 'url': 'https://m.anjuke.com/tlf/xiaoqu/'},
    {'city': '天门', 'url': 'https://m.anjuke.com/tm/xiaoqu/'},
    {'city': '图木舒克', 'url': 'https://m.anjuke.com/tmsk/xiaoqu/'},
    {'city': '桐城', 'url': 'https://m.anjuke.com/tongc/xiaoqu/'},
    {'city': '铜仁', 'url': 'https://m.anjuke.com/tr/xiaoqu/'},
    {'city': '台湾', 'url': 'https://m.anjuke.com/tw/xiaoqu/'},
    {'city': '太仓', 'url': 'https://m.anjuke.com/taicang/xiaoqu/'},
    {'city': '泰兴', 'url': 'https://m.anjuke.com/taix/xiaoqu/'},
    {'city': '滕州', 'url': 'https://m.anjuke.com/tzs/xiaoqu/'},
    {'city': '洮南', 'url': 'https://m.anjuke.com/tn/xiaoqu/'},
    {'city': '铁力', 'url': 'https://m.anjuke.com/tiel/xiaoqu/'},
    {'city': '桐乡', 'url': 'https://m.anjuke.com/tx/xiaoqu/'},
    {'city': '天长', 'url': 'https://m.anjuke.com/tch/xiaoqu/'},

    {'city': '无锡', 'url': 'https://m.anjuke.com/wx/xiaoqu/'},
    {'city': '威海', 'url': 'https://m.anjuke.com/wei/xiaoqu/'},
    {'city': '潍坊', 'url': 'https://m.anjuke.com/wf/xiaoqu/'},
    {'city': '乌鲁木齐', 'url': 'https://m.anjuke.com/wlmq/xiaoqu/'},
    {'city': '温州', 'url': 'https://m.anjuke.com/wz/xiaoqu/'},
    {'city': '芜湖', 'url': 'https://m.anjuke.com/wuh/xiaoqu/'},
    {'city': '梧州', 'url': 'https://m.anjuke.com/wu/xiaoqu/'},
    {'city': '渭南', 'url': 'https://m.anjuke.com/wn/xiaoqu/'},
    {'city': '乌海', 'url': 'https://m.anjuke.com/wuhai/xiaoqu/'},
    {'city': '文山', 'url': 'https://m.anjuke.com/ws/xiaoqu/'},
    {'city': '武威', 'url': 'https://m.anjuke.com/wuwei/xiaoqu/'},
    {'city': '乌兰察布', 'url': 'https://m.anjuke.com/wlcb/xiaoqu/'},
    {'city': '瓦房店', 'url': 'https://m.anjuke.com/wfd/xiaoqu/'},
    {'city': '五家渠', 'url': 'https://m.anjuke.com/wjq/xiaoqu/'},
    {'city': '武夷山', 'url': 'https://m.anjuke.com/wys/xiaoqu/'},
    {'city': '吴忠', 'url': 'https://m.anjuke.com/wuz/xiaoqu/'},
    {'city': '五指山', 'url': 'https://m.anjuke.com/wzs/xiaoqu/'},
    {'city': '中卫', 'url': 'https://m.anjuke.com/zw/xiaoqu/'},
    {'city': '温岭', 'url': 'https://m.anjuke.com/wls/xiaoqu/'},
    {'city': '武安', 'url': 'https://m.anjuke.com/was/xiaoqu/'},
    {'city': '舞钢', 'url': 'https://m.anjuke.com/wg/xiaoqu/'},
    {'city': '五常', 'url': 'https://m.anjuke.com/wuch/xiaoqu/'},
    {'city': '卫辉', 'url': 'https://m.anjuke.com/weih/xiaoqu/'},
    {'city': '武冈', 'url': 'https://m.anjuke.com/wug/xiaoqu/'},
    {'city': '文昌', 'url': 'https://m.anjuke.com/wenchangshi/xiaoqu/'},
    {'city': '五大连池', 'url': 'https://m.anjuke.com/wdlc/xiaoqu/'},
    {'city': '乌兰浩特', 'url': 'https://m.anjuke.com/wlht/xiaoqu/'},
    {'city': '武穴', 'url': 'https://m.anjuke.com/wux/xiaoqu/'},
    {'city': '万源', 'url': 'https://m.anjuke.com/wy/xiaoqu/'},
    {'city': '吴川', 'url': 'https://m.anjuke.com/wuchuan/xiaoqu/'},
    {'city': '万宁', 'url': 'https://m.anjuke.com/wann/xiaoqu/'},
    {'city': '西安', 'url': 'https://m.anjuke.com/xa/xiaoqu/'},
    {'city': '厦门', 'url': 'https://m.anjuke.com/xm/xiaoqu/'},
    {'city': '徐州', 'url': 'https://m.anjuke.com/xz/xiaoqu/'},
    {'city': '湘潭', 'url': 'https://m.anjuke.com/xiang/xiaoqu/'},
    {'city': '襄阳', 'url': 'https://m.anjuke.com/xy/xiaoqu/'},
    {'city': '新乡', 'url': 'https://m.anjuke.com/xx/xiaoqu/'},
    {'city': '信阳', 'url': 'https://m.anjuke.com/xiny/xiaoqu/'},
    {'city': '咸阳', 'url': 'https://m.anjuke.com/xiany/xiaoqu/'},
    {'city': '邢台', 'url': 'https://m.anjuke.com/xt/xiaoqu/'},
    {'city': '孝感', 'url': 'https://m.anjuke.com/xg/xiaoqu/'},
    {'city': '西宁', 'url': 'https://m.anjuke.com/xn/xiaoqu/'},
    {'city': '许昌', 'url': 'https://m.anjuke.com/xc/xiaoqu/'},
    {'city': '忻州', 'url': 'https://m.anjuke.com/xin/xiaoqu/'},
    {'city': '宣城', 'url': 'https://m.anjuke.com/xuan/xiaoqu/'},
    {'city': '咸宁', 'url': 'https://m.anjuke.com/xiann/xiaoqu/'},
    {'city': '兴安盟', 'url': 'https://m.anjuke.com/xam/xiaoqu/'},
    {'city': '新余', 'url': 'https://m.anjuke.com/xinyu/xiaoqu/'},
    {'city': '香港', 'url': 'https://m.anjuke.com/hongk/xiaoqu/'},
    {'city': '湘西', 'url': 'https://m.anjuke.com/xiangx/xiaoqu/'},
    {'city': '仙桃', 'url': 'https://m.anjuke.com/xiant/xiaoqu/'},
    {'city': '锡林郭勒盟', 'url': 'https://m.anjuke.com/xl/xiaoqu/'},
    {'city': '新泰', 'url': 'https://m.anjuke.com/xts/xiaoqu/'},
    {'city': '新乐', 'url': 'https://m.anjuke.com/xle/xiaoqu/'},
    {'city': '湘乡', 'url': 'https://m.anjuke.com/xix/xiaoqu/'},
    {'city': '锡林浩特', 'url': 'https://m.anjuke.com/xlht/xiaoqu/'},
    {'city': '辛集', 'url': 'https://m.anjuke.com/xji/xiaoqu/'},
    {'city': '新民', 'url': 'https://m.anjuke.com/xim/xiaoqu/'},
    {'city': '兴化', 'url': 'https://m.anjuke.com/xh/xiaoqu/'},
    {'city': '兴平', 'url': 'https://m.anjuke.com/xp/xiaoqu/'},
    {'city': '兴义', 'url': 'https://m.anjuke.com/xingy/xiaoqu/'},
    {'city': '宣威', 'url': 'https://m.anjuke.com/xuanw/xiaoqu/'},
    {'city': '兴宁', 'url': 'https://m.anjuke.com/xingn/xiaoqu/'},
    {'city': '项城', 'url': 'https://m.anjuke.com/xiangch/xiaoqu/'},
    {'city': '信宜', 'url': 'https://m.anjuke.com/xinyishi/xiaoqu/'},
    {'city': '孝义', 'url': 'https://m.anjuke.com/xiaoy/xiaoqu/'},
    {'city': '兴城', 'url': 'https://m.anjuke.com/xingch/xiaoqu/'},
    {'city': '新沂', 'url': 'https://m.anjuke.com/xinyi/xiaoqu/'},
    {'city': '荥阳', 'url': 'https://m.anjuke.com/xing/xiaoqu/'},
    {'city': '新郑', 'url': 'https://m.anjuke.com/xzh/xiaoqu/'},
    {'city': '新密', 'url': 'https://m.anjuke.com/xinm/xiaoqu/'},
    {'city': '烟台', 'url': 'https://m.anjuke.com/yt/xiaoqu/'},
    {'city': '扬州', 'url': 'https://m.anjuke.com/yz/xiaoqu/'},
    {'city': '宜昌', 'url': 'https://m.anjuke.com/yi/xiaoqu/'},
    {'city': '银川', 'url': 'https://m.anjuke.com/yin/xiaoqu/'},
    {'city': '阳江', 'url': 'https://m.anjuke.com/yj/xiaoqu/'},
    {'city': '永州', 'url': 'https://m.anjuke.com/yong/xiaoqu/'},
    {'city': '玉林', 'url': 'https://m.anjuke.com/yu/xiaoqu/'},
    {'city': '盐城', 'url': 'https://m.anjuke.com/yan/xiaoqu/'},
    {'city': '岳阳', 'url': 'https://m.anjuke.com/yy/xiaoqu/'},
    {'city': '运城', 'url': 'https://m.anjuke.com/yun/xiaoqu/'},
    {'city': '宜春', 'url': 'https://m.anjuke.com/ych/xiaoqu/'},
    {'city': '营口', 'url': 'https://m.anjuke.com/yk/xiaoqu/'},
    {'city': '榆林', 'url': 'https://m.anjuke.com/yl/xiaoqu/'},
    {'city': '宜宾', 'url': 'https://m.anjuke.com/yb/xiaoqu/'},
    {'city': '益阳', 'url': 'https://m.anjuke.com/yiy/xiaoqu/'},
    {'city': '义乌', 'url': 'https://m.anjuke.com/yw/xiaoqu/'},
    {'city': '玉溪', 'url': 'https://m.anjuke.com/yx/xiaoqu/'},
    {'city': '伊犁', 'url': 'https://m.anjuke.com/yili/xiaoqu/'},
    {'city': '阳泉', 'url': 'https://m.anjuke.com/yq/xiaoqu/'},
    {'city': '延安', 'url': 'https://m.anjuke.com/yanan/xiaoqu/'},
    {'city': '鹰潭', 'url': 'https://m.anjuke.com/ying/xiaoqu/'},
    {'city': '延边', 'url': 'https://m.anjuke.com/yanb/xiaoqu/'},
    {'city': '云浮', 'url': 'https://m.anjuke.com/yf/xiaoqu/'},
    {'city': '雅安', 'url': 'https://m.anjuke.com/ya/xiaoqu/'},
    {'city': '阳春', 'url': 'https://m.anjuke.com/yang/xiaoqu/'},
    {'city': '鄢陵', 'url': 'https://m.anjuke.com/yanl/xiaoqu/'},
    {'city': '伊春', 'url': 'https://m.anjuke.com/yichuns/xiaoqu/'},
    {'city': '玉树', 'url': 'https://m.anjuke.com/ys/xiaoqu/'},
    {'city': '乐清', 'url': 'https://m.anjuke.com/yue/xiaoqu/'},
    {'city': '禹州', 'url': 'https://m.anjuke.com/yuzh/xiaoqu/'},
    {'city': '永新', 'url': 'https://m.anjuke.com/yxx/xiaoqu/'},
    {'city': '永康', 'url': 'https://m.anjuke.com/yks/xiaoqu/'},
    {'city': '榆树', 'url': 'https://m.anjuke.com/yush/xiaoqu/'},
    {'city': '永安', 'url': 'https://m.anjuke.com/yonga/xiaoqu/'},
    {'city': '宜都', 'url': 'https://m.anjuke.com/yd/xiaoqu/'},
    {'city': '仪征', 'url': 'https://m.anjuke.com/yizh/xiaoqu/'},
    {'city': '延吉', 'url': 'https://m.anjuke.com/yanj/xiaoqu/'},
    {'city': '扬中', 'url': 'https://m.anjuke.com/yzh/xiaoqu/'},
    {'city': '伊宁', 'url': 'https://m.anjuke.com/yiningshi/xiaoqu/'},
    {'city': '永济', 'url': 'https://m.anjuke.com/yongj/xiaoqu/'},
    {'city': '应城', 'url': 'https://m.anjuke.com/yingchengs/xiaoqu/'},
    {'city': '宜州', 'url': 'https://m.anjuke.com/yizhou/xiaoqu/'},
    {'city': '英德', 'url': 'https://m.anjuke.com/yingd/xiaoqu/'},
    {'city': '玉门', 'url': 'https://m.anjuke.com/ym/xiaoqu/'},
    {'city': '禹城', 'url': 'https://m.anjuke.com/yuch/xiaoqu/'},
    {'city': '余姚', 'url': 'https://m.anjuke.com/yuy/xiaoqu/'},
    {'city': '偃师', 'url': 'https://m.anjuke.com/yss/xiaoqu/'},
    {'city': '永城', 'url': 'https://m.anjuke.com/yoche/xiaoqu/'},
    {'city': '宜兴', 'url': 'https://m.anjuke.com/yix/xiaoqu/'},
    {'city': '宜城', 'url': 'https://m.anjuke.com/yiche/xiaoqu/'},
    {'city': '沅江', 'url': 'https://m.anjuke.com/yjiang/xiaoqu/'},
    {'city': '郑州', 'url': 'https://m.anjuke.com/zz/xiaoqu/'},
    {'city': '珠海', 'url': 'https://m.anjuke.com/zh/xiaoqu/'},
    {'city': '中山', 'url': 'https://m.anjuke.com/zs/xiaoqu/'},
    {'city': '镇江', 'url': 'https://m.anjuke.com/zj/xiaoqu/'},
    {'city': '淄博', 'url': 'https://m.anjuke.com/zb/xiaoqu/'},
    {'city': '张家口', 'url': 'https://m.anjuke.com/zjk/xiaoqu/'},
    {'city': '株洲', 'url': 'https://m.anjuke.com/zhu/xiaoqu/'},
    {'city': '漳州', 'url': 'https://m.anjuke.com/zhang/xiaoqu/'},
    {'city': '湛江', 'url': 'https://m.anjuke.com/zhan/xiaoqu/'},
    {'city': '肇庆', 'url': 'https://m.anjuke.com/zq/xiaoqu/'},
    {'city': '枣庄', 'url': 'https://m.anjuke.com/zao/xiaoqu/'},
    {'city': '舟山', 'url': 'https://m.anjuke.com/zhou/xiaoqu/'},
    {'city': '遵义', 'url': 'https://m.anjuke.com/zy/xiaoqu/'},
    {'city': '驻马店', 'url': 'https://m.anjuke.com/zmd/xiaoqu/'},
    {'city': '自贡', 'url': 'https://m.anjuke.com/zg/xiaoqu/'},
    {'city': '资阳', 'url': 'https://m.anjuke.com/zi/xiaoqu/'},
    {'city': '周口', 'url': 'https://m.anjuke.com/zk/xiaoqu/'},
    {'city': '章丘', 'url': 'https://m.anjuke.com/zhq/xiaoqu/'},
    {'city': '张家界', 'url': 'https://m.anjuke.com/zjj/xiaoqu/'},
    {'city': '诸城', 'url': 'https://m.anjuke.com/zc/xiaoqu/'},
    {'city': '庄河', 'url': 'https://m.anjuke.com/pld/xiaoqu/'},
    {'city': '正定', 'url': 'https://m.anjuke.com/zd/xiaoqu/'},
    {'city': '张北', 'url': 'https://m.anjuke.com/zhangb/xiaoqu/'},
    {'city': '张掖', 'url': 'https://m.anjuke.com/zhangy/xiaoqu/'},
    {'city': '昭通', 'url': 'https://m.anjuke.com/zt/xiaoqu/'},
    {'city': '赵县', 'url': 'https://m.anjuke.com/zx/xiaoqu/'},
    {'city': '邹城', 'url': 'https://m.anjuke.com/zcs/xiaoqu/'},
    {'city': '遵化', 'url': 'https://m.anjuke.com/zunh/xiaoqu/'},
    {'city': '肇东', 'url': 'https://m.anjuke.com/zhd/xiaoqu/'},
    {'city': '张家港', 'url': 'https://m.anjuke.com/zhjg/xiaoqu/'},
    {'city': '枝江', 'url': 'https://m.anjuke.com/zhij/xiaoqu/'},
    {'city': '招远', 'url': 'https://m.anjuke.com/zhys/xiaoqu/'},
    {'city': '钟祥', 'url': 'https://m.anjuke.com/zhx/xiaoqu/'},
    {'city': '资兴', 'url': 'https://m.anjuke.com/zixing/xiaoqu/'},
    {'city': '樟树', 'url': 'https://m.anjuke.com/zhsh/xiaoqu/'},
    {'city': '扎兰屯', 'url': 'https://m.anjuke.com/zhld/xiaoqu/'},
    {'city': '诸暨', 'url': 'https://m.anjuke.com/zhj/xiaoqu/'},
    {'city': '涿州', 'url': 'https://m.anjuke.com/zzs/xiaoqu/'},
    {'city': '枣阳', 'url': 'https://m.anjuke.com/zys/xiaoqu/'},
    {'city': '漳平', 'url': 'https://m.anjuke.com/zhp/xiaoqu/'}]
